package org.example;

public enum bookingMainMenu {
    QUIT_BOOKING_MENU,
    ADD_BOOKING,
    EDIT_BOOKING,
    DELETE_BOOKING,
    PRINT_BOOKING_BY_BOOKING_ID,
    PRINT_ALL_BOOKINGS,
    PRINT_DATE_TIME_ORDER,
    RETURN_COMPUTER,
    AVERAGE_BOOKING_LENGTH,
    BOOKING_STATISTICS;
}
